pub mod agent;
pub mod attach;
pub mod config;
pub mod error;
pub mod git;
pub mod model;
pub mod monitor;
pub mod plugins;
pub mod store;
pub mod terminal;
pub mod tui;
pub mod wagner;

pub use agent::{Agent, ClaudeCode, ClaudeCodeDetector, TestAgent};
pub use attach::{detect_attach_mode, derive_task_name, AttachDetection};
pub use config::Config;
pub use error::{Result, WagnerError};
pub use model::{RepoSource, Task, TaskKind, TaskRepo};
pub use store::Store;
pub use terminal::{MockTerminal, PaneHandle, SessionHandle, Terminal, Tmux};
pub use wagner::{RepoSpec, Wagner, default_branch_for_task};
